mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("polls/", include("polls.urls")),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.index,name='index'),
    path("<int:question_id>/", views.detail, name='details'),
    path("<int:question_id>/results/", views.results, name='results'),
    # path("<int:question_id>/votes/", views.vote, name='votes'),
]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime


# Create your models here.

class Question(models.Model): 
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return f"{self.question_text} {self.pub_date.isoformat()}"

    def publish_recent(self): 
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model): 
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.question} {self.votes} {self.choice_text}"

polls/views.py
from django.http import HttpResponse
from .models import Question
from django.shortcuts import render, get_object_or_404

def index(request): 
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = {"latest_question_list": latest_question_list}
    return render(request, "polls/index.html", context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/details.html", {"question": question})

def results(request, question_id):
    get_question = get_object_or_404(Question, pk=question_id)
    list_result = get_question.choice_set.all()
    return render(request, "polls/results.html", {'question': get_question, 'choices': list_result})

# def vote(request, question_id):
#     question = get_object_or_404(Question, )
#     return HttpResponse("You're voting on question %s." % question_id)

polls/templates/polls/details.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:details' question_id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>
<ul>
  {% for choice in choices %}
    <li>{{ choice.choice_text }} - {{ choice.votes }} votes</li>
  {% endfor %}
</ul>